### ISSUE TITLE
Version included from svSocket does not have backwards compatibility for some functions

### ISSUE THREAD

**Issue by epicfaace** [SciViews/svMisc#1]
When I am using svSocket, I get errors saying that ```parseText``` and ```captureAll``` are not found. Perhaps the backwards compatibility for these svMisc functions is not working properly?

I have to do this to make it work:
```
require("svSocket")
parseText <- parse_text
captureAll <- capture_all
```

**Comment by phgrosjean** [comment]
Yes, you are right. Those functions are defined, but not exported in 1.0-1. Corrected in 1.0-2 that will percolate to CRAN as soon as possible.
Thanks
