### ISSUE TITLE
The progress() function works just once

### ISSUE THREAD

**Issue by ManuelPopp** [SciViews/svMisc#2]
Hi there,
I recently started using the _progress()_ function to monitor longer tasks and I found that when running a loop multiple times, the progress bar is only displayed the first time.
I tried to _rm(i)_ but the counting variable wasn't the issue...

**Comment by phgrosjean** [comment]
Could you provide a small working example, please?

**Comment by ManuelPopp** [comment]
```
require("svMisc")
# run the following twice
for(i in 1:50){
  i^2
  Sys.sleep(1)
  progress(value = i, progress.bar = TRUE, max.value = 50)
}
```

**Comment by phgrosjean** [comment]
Yes, you need to dismiss the previous progress bar by calling `progress(value = 51, progress.bar = TRUE, max.value = 50)`, that is, with a value higher than the max, as it is the case in the examples. Only then, you can display a second progress bar.
