### ISSUE TITLE
Return completion addition as a separate field

### ISSUE THREAD

**Issue by rhuffy** [SciViews/svMisc#3]
Currently, setting `addition=TRUE` returns the addition substring instead of the full name of the completion. Can this be changed to return the addition string as a separate field, so that both the full name and the addition string are returned for each completion?

Would be happy to contribute this, possibly by introducing a new param `completion.option=c('name','addition','both')` to avoid a breaking change.

**Comment by phgrosjean** [comment]
Could you submit a pull request?
